export const SET_COMPANIES = 'SET_COMPANIES';
export const SET_COMPANIES_GET_REQUEST_LOADING = 'SET_COMPANIES_GET_REQUEST_LOADING';
export const SET_COMPANIES_GET_REQUEST_SUCCESS = 'SET_COMPANIES_GET_REQUEST_SUCCESS';
export const SET_COMPANIES_GET_REQUEST_ERROR = 'SET_COMPANIES_GET_REQUEST_ERROR';
export const RESET_STORE = 'RESET_STORE';