export const SET_ITEMS = 'SET_ITEMS';
export const SET_ITEMS_GET_REQUEST_LOADING = 'SET_ITEMS_GET_REQUEST_LOADING';
export const SET_ITEMS_GET_REQUEST_SUCCESS = 'SET_ITEMS_GET_REQUEST_SUCCESS';
export const SET_ITEMS_GET_REQUEST_ERROR = 'SET_ITEMS_GET_REQUEST_ERROR';
export const RESET_STORE = 'RESET_STORE';